server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monolithic?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
      hibernate:
       ddl-auto: update
      show-sql: true

  outbound:
    client-id: "59080131813-jk3cpt412lo0dkbkv3t20r7pufc56rcg.apps.googleusercontent.com"
    secret-id: "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"
    uri-redirect: "http://localhost:3000/authenticate"
    grant-type: authorization_code



jwt:
  signerKey: "5mM3D6IjAIq7CJaVJo3Q8Jfri0uA3nxpTu5ZbND3n/ZUzIsfxpiiraSHIm+eXh8L"
  valid-duration: 300000 #in second
  refreshable-duration: 500000 #in second

