server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/monolithic"
    username: "root"
    password: "root"
  jpa:
      hibernate:
       ddl-auto: update
      show-sql: true


jwt:
  signerKey: "5mM3D6IjAIq7CJaVJo3Q8Jfri0uA3nxpTu5ZbND3n/ZUzIsfxpiiraSHIm+eXh8L"
  valid-duration: 30 #in second
  refreshable-duration: 50 #in second